// Auto-generated by pre-push hook — elle düzenleme yapma
import Foundation

enum BuildInfo {
    static let branch     = "release/v1.0.0-2026-05-24"
    static let commitHash = "c82722a"
    static let buildDate  = "25.05.2026"

    /// Ayarlar ekranında gösterilecek versiyon metni
    static let displayVersion: String = {
        let name = branch.replacingOccurrences(of: "release/", with: "")
                         .replacingOccurrences(of: "claude/", with: "")
        return name
    }()
}
