// Auto-generated by pre-push hook — elle düzenleme yapma
import Foundation

enum BuildInfo {
    static let branch     = "release/v1.0.0-2026-05-24"
    static let commitHash = "0f092cd"
    static let buildDate  = "31.05.2026"

    /// Ayarlar ekranında gösterilecek versiyon metni (sondaki -YYYY-MM-DD tarih eki çıkarılır)
    static let displayVersion: String = {
        let name = branch.replacingOccurrences(of: "release/", with: "")
                         .replacingOccurrences(of: "claude/", with: "")
        return name.replacingOccurrences(
            of: #"-\d{4}-\d{2}-\d{2}$"#,
            with: "",
            options: .regularExpression
        )
    }()
}
